### ISSUE TITLE
Ability to Spray Multiple Tenants

### ISSUE THREAD

**Issue by puzzlepeaches** [MarkoH17/Spray365#10]
**Describe The Problem To Be Solved**
Currently, the user has to start separate Spray365 instances if targeting multiple organizations/tenants. 

Additionally, smart-lockout controls could potentially lean on the fact that multiple failed attempts are occurring in succession for a single organization. 

**Suggested Solution**
To fix this issue, Spray365 should allow for:

* The creation of execution plans targeting multiple domains with a much larger list of users
* The creation of execution plans using a user list containing emails. Currently, the domain for the targeted tenant must be specified using a separate CLI flag
* Show the specific domain being targeted in stdout

Again, similar to the other issue I created, getting a handle on where I would implement this functionality is proving difficult. Let me know your thoughts on this and if I can provide any assistance. Thanks!

**Comment by MarkoH17** [comment]
@puzzlepeaches, 

Adding the ability to spray multiple tenants is a great idea! This seems like a pretty small change to make, but we have to consider how it will affect shuffled execution plans. For example, should spraying multiple tenants affect shuffled execution plans (`--shuffle_auth_order`)?

I imagine adding support to spray multiple tenants basically involves updating execution plan generation logic to support pulling the "domain" (tenant) from the user-supplied file containing the list of usernames. The list of users [are pulled before](https://github.com/MarkoH17/Spray365/blob/main/modules/generate/modes/normal.py#L51,L55) the "credential" [objects are built](https://github.com/MarkoH17/Spray365/blob/main/modules/generate/helpers.py#L162,L170), so this change will require some refactoring in several places:
- [`helpers.get_users_and_passwords`](https://github.com/MarkoH17/Spray365/blob/main/modules/generate/helpers.py#L24): Support pulling domain from input list of users when `--passwords_in_userfile` is specified
- [`helpers.get_users`](https://github.com/MarkoH17/Spray365/blob/main/modules/generate/helpers.py#L54): Support pulling domain from input list of users when `--passwords_in_userfile` is _NOT_ specified
- [`helpers.get_credentials`](https://github.com/MarkoH17/Spray365/blob/main/modules/generate/helpers.py#L129): Support pulling domain from input list of users instead of `-d / --domain` argument

I think its important to allow users to still only spray a single domain (`-d / --domain`), so this change should still support that password spraying approach. It seems like these spraying approaches are mutually exclusive (single / multi-tenant), so this enhancement can likely be exposed through a new mutually-exclusive option group ([here's an example](https://github.com/MarkoH17/Spray365/blob/58fd19352643e8605e2f665f220cb610539e9f69/modules/generate/options.py#L53,L68)).

Please feel free to take a swing at this, as it might be awhile until I get around to adding this enhancement. If you run into any issues or have any questions, let's continue the discussion here.

Cheers!

**Comment by puzzlepeaches** [comment]
We can close this out. I'm making the requested changes [here](https://github.com/puzzlepeaches/Spray365/tree/packaged). Feel free to check them out when you get some time!
