### ISSUE TITLE
Mode to check valid accounts against all CAP?

### ISSUE THREAD

**Issue by vysecurity** [MarkoH17/Spray365#4]
Hi there, is there a mode to check all valid accounts against all CAP conditions?

**Comment by MarkoH17** [comment]
Hey @vysecurity,

Currently there is not a mode to check known-valid accounts against conditional access policies. I think this may be accomplished by adding two flags to the spray function:

- Username and Password File (`--userpassfile / -up`): This flag would allow the user to supply a path to a file containing the username / password combinations. For this use case, it should container known-valid passwords for the accounts.
- All AAD Client / Endpoint IDs (`--all_aad_combos / -aac`): This flag would cause each credential to authenticate against all AAD client and AAD endpoint IDs. This may (or may not) reveal holes in conditional access policies.

Adding the above two features should allow users to check valid accounts against conditional access policies. Did you have another implementation in mind, or do you think this would satisfy the use case?

**Comment by vysecurity** [comment]
Hey @MarkoH17,

I'll give it a shot. What I was looking for more on the lines of was checking every time of OS, Browser/App, against the policies. Not sure if that's what point 2 you're talking about here refers to.

I'll try it now and get back to you.

**Comment by MarkoH17** [comment]
@vysecurity ,

Yeah, point 2 was referencing generating combinations of browsers (user-agents), endpoint ids (target resource), and client id (requestor). 

Keep in mind the two proposed flags above don't exist yet in Spray365, but it's something that I may be able to look into.

**Comment by vysecurity** [comment]
> @vysecurity ,
> 
> Yeah, point 2 was referencing generating combinations of browsers (user-agents), endpoint ids (target resource), and client id (requestor).
> 
> Keep in mind the above options don't exist yet in Spray365, but it's something that I may be able to look into.

Oh right yes, all_aad_combos is probably what I'm looking for. I just checked and realised that the flag doesn't exist and noticed your comment 😄

**Comment by MarkoH17** [comment]
@vysecurity

:) It's a great idea for a feature addition.

These would actually be features to add to the generate mode, since they would affect how the execution plan is created.

In the meantime, you may be able to generate your own JSON file (execution plan) that contains the username/password pairs for all desired combinations of user-agent, AAD client ID, and AAD endpoint ID. The execution plan just needs to contain an array of credential objects. Below is a sample execution plan:

``` jsonc
[
    {
        "domain": "example.com",
        "username": "john_doe",
        "password": "password2022",
        "client_id": [
            "aad_pinredemption",
            "06c6433f-4fb8-4670-b2cd-408938296b8e"
        ],
        "endpoint": [
            "azure_mgmt_api",
            "https://management.azure.com"
        ],
        "user_agent": [
            "default",
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36"
        ],
        "delay": 30,
        "initial_delay": 0
    },
    {
        "domain": "example.com",
        "username": "john_doe",
        "password": "password123",
        "client_id": [
            "aad_brokerplugin",
            "6f7e0f60-9401-4f5b-98e2-cf15bd5fd5e3"
        ],
        "endpoint": [
            "aad_graph_api",
            "https://graph.windows.net"
        ],
        "user_agent": [
            "default",
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36"
        ],
        "delay": 30,
        "initial_delay": 0
    }
]
```

**Comment by vysecurity** [comment]
Right, I'll figure out if there's a way to grab all combinations and create an EP.

Basically we want to try every combination of: 
* win_ie11_win8->ms_authenticator->azure_mgmt_api

Any easy way to generate the execution plan of all those combinations?

Offtopic, but do you know what `msmamservice` is?

**Comment by MarkoH17** [comment]
I'll see about putting together a PoC for generating a custom execution plan.

`msmamservice` looks to be related to Microsoft's Intune [Mobile Application Management](https://docs.microsoft.com/en-us/mem/intune/apps/mam-faq). I am not sure how this endpoint/client is used in real-world scenarios.

**Comment by vysecurity** [comment]
> I'll see about putting together a PoC for generating a custom execution plan.
> 
> `msmamservice` looks to be related to Microsoft's Intune [Mobile Application Management](https://docs.microsoft.com/en-us/mem/intune/apps/mam-faq). I am not sure how this endpoint/client is used in real-world scenarios.

I'd had thought it would have just been 3 for loops :-)

Temporary Solution, I modified the credential generation to:

```
 for i in range(0,len(client_id_values)):
                for j in range(0,len(endpoint_id_values)):
                    for k in range(0,len(user_agent_values)):
                        combinations.append(
                            Credential(domain, username, password, client_id_values[i], endpoint_id_values[j], user_agent_values[k], delay))
```

**Comment by MarkoH17** [comment]
@vysecurity,

[Version 0.2.0-beta](https://github.com/MarkoH17/Spray365/releases/tag/0.2.0-beta) of Spray365 added an `audit` type to `generate` mode. Audit-type execution plans can be used to generate execution plans to identify issues with MFA / CAP configurations. 

This new version also added the option `--passwords_in_userfile`, which allows users to provide a specific password for each user in the `user_file`. You can try to generate an audit-type execution plan using the following:

`python spray365.py generate audit -ep <output_filename> -u <users_file> --passwords_in_usersfile -d <domain>`. The audit-type execution plans can be sprayed just like a normal execution plan: `python spray365.py spray -ep <execution_plan_filename>`. 

Finally, this new version added a "review" mode, which allows users to see a summarized view of the spray results.

`python spray365.py review --help`. 

Note: This new version refactored the Credential, AuthResult, and AuthError objects. This means that only new execution plan and results can be processed using v0.2.0-beta.

Please open a new issue if you run into any problems; in the meantime, I'm closing this issue since c16ba519d949b72d9936b2966f6fa66c483a7a89 resolves this.
