### ISSUE TITLE
Spray365 treating Lockouts and Disabled accounts as 'partial success'

### ISSUE THREAD

**Issue by vysecurity** [MarkoH17/Spray365#6]
Locked accounts and disabled account passwords have not been checked, so it's not technically a partial success.

**Comment by MarkoH17** [comment]
@vysecurity 

This behavior is by design; accounts can only be identified as disabled or locked out if valid credentials were identified. This is considered a partial success because this means valid credentials were identified, but access to the account was prevented.

**Comment by MarkoH17** [comment]
The only other thing I would note would be that password spraying protections in Azure AD sometimes falsely report an account is locked out. However, there is no way that I can see how to differentiate whether an account is legitimately locked out or not.

**Comment by vysecurity** [comment]
Yep what I’m saying is, if the account is locked or disabled, it won’t even check the password validity. It doesn’t mean that the credentials are correct.

**Comment by MarkoH17** [comment]
@vysecurity ,

The only way Spray365 knows if an account is disabled or locked out is by attempting to authenticate

**Comment by vysecurity** [comment]
Yeah, it attempts to auth, ignores whether the password is correct or not and shows the account locked or disabled message if it's locked or disabled.

**Comment by MarkoH17** [comment]
@vysecurity ,

My original re-opening comment got cut-off when I was re-opening the issue. Here is my reply: 

> Yep what I’m saying is, if the account is locked or disabled, it won’t even check the password validity. It doesn’t mean that the credentials are correct.

The only way Spray365 knows if an account is locked out or disabled is by [attempting to authenticate](https://github.com/MarkoH17/Spray365/blob/main/modules/spray/helpers.py#L48) using the provided credentials.  



> Yeah, it attempts to auth, ignores whether the password is correct or not and shows the account locked or disabled message if it's locked or disabled.

This is the intended behavior because Spray365 cannot tell (from MSAL) whether the password was valid or not. How would you suggest this be improved?

**Comment by MarkoH17** [comment]
This may clear things up... Below is a screenshot of the POST request intercepted in BurpSuite after Spray365 [attempts authentication](https://github.com/MarkoH17/Spray365/blob/main/modules/spray/helpers.py#L48).

I don't have a disabled/locked-out account to test against, but I think this is a decent example. We attempt authentication in the POST request, and process the `error_codes` in the response to identify whether the credentials were valid (no errors), invalid (error: 50034), disabled (error: 50057), or the account was locked out (error: 50053). 

Re-attempting authentication with another set of credentials for the same account would not yield any different result for accounts that are locked out or disabled.

<img width="959" alt="image" src="https://user-images.githubusercontent.com/8473031/169931626-8b4727ca-dd78-42d1-91d6-a4a9baca438e.png">

**Comment by MarkoH17** [comment]
@vysecurity ,

I think I see the issue - sorry it took me so long! 

I believe you are suggesting that locked out accounts and disabled accounts should not be treated as [partial successes](https://github.com/MarkoH17/Spray365/blob/main/modules/core/constants.py#L83).

I still believe that disabled account should be treated as partial successes. However, because of the high number of lockout false-positives, it may make sense to remove it. What are your thoughts?

**Comment by vysecurity** [comment]
The reason I suggest it is because smart lockout doesn’t really work well against a IP rotating proxy and slow attack. I sprayed 4000 accounts a day at around 5 seconds a try and never had any issues.

**Comment by MarkoH17** [comment]
Closing this issue for now. Here are the list of [AAD STS error codes](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-aadsts-error-codes#aadsts-error-codes) that will result in a "partial success": [`constants.auth_partial_success_error_codes`](https://github.com/MarkoH17/Spray365/blob/58fd19352643e8605e2f665f220cb610539e9f69/modules/core/constants.py#L83)

I feel it is important to point out these results because they may be useful in other contexts. AFAIK, there is no way to tell whether an "Account Locked" response is legitimate, or caused by Azure Smart Lockout (false positive).

As @vysecurity mentioned, using Spray365 with a slower throughput (longer delay) and a proxy which rotates the source IP address is often enough to bypass the false positives returned by Azure Smart Lockout.
